# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            cwiggs.github.io
tagline:          Cwiggs Personal site
url:              http://cwiggs.github.io
paginate:         1
baseurl:          /
author:
  name:           Chris Wiggins
#  url:            https://twitter.com/mdo
  email:          chrisonline1991@gmail.com
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
